version: '2'
services:
  icinga2:
    image: bebehei/icinga2-client
    restart: on-failure:5
    hostname: icinga2
    environment:
      #- ICINGA2_USER_FULLNAME=Icinga2 Docker Monitoring Instance
    volumes:
      - ./cache:/var/cache/icinga2
      - ./certs:/etc/apache2/ssl:ro
      - ./etc/icinga2:/etc/icinga2
      - ./lib/icinga:/var/lib/icinga2
      - ./log/icinga2:/var/log/icinga2
      - ./log/mysql:/var/log/mysql
      - ./spool:/var/spool/icinga2
      # If you want to enable outbound e-mail, create the files
      #  - ./ssmtp/ssmtp.conf
      #  - ./ssmtp/revaliases
      #  and configure to your corresponding mail setup.
      #  See: https://github.com/jjethwa/icinga2#sending-notification-mails
      #- ./ssmtp/revaliases:/etc/ssmtp/revaliases:ro
      #- ./ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf:ro
