version: '2'
services:
  icinga2:
    image: bebehei/icinga2-client
    restart: on-failure:5
    hostname: icinga2
    privileged: true
    network_mode: host
    volumes:
      - ./cache:/var/cache/icinga2
      - ./certs:/etc/apache2/ssl:ro
      - ./etc/icinga2:/etc/icinga2
      - ./lib/icinga:/var/lib/icinga2
      - ./log/icinga2:/var/log/icinga2
      - ./log/mysql:/var/log/mysql
      - ./spool:/var/spool/icinga2
